### ISSUE TITLE
支付宝登录报错

### ISSUE THREAD

**Issue by LiveIsLive** [netnr/Netnr.Login#7]
在支付宝的页面登录成功后，返回到自己的网站的登录回调页面报错。

这是其中的一个报错请求网址：
Login?auth_code=fa8cb66cd17c409eb5fcb889b84aHX06&type=5&returnUrl=https%3A%2F%2Fcore-hosting.net%2FControlPanel&app_id=2021001109609069&source=alipay_wallet&scope=auth_user&state=login_20241016105709510

接收的的Controller：
public async Task<bool> Login(Netnr.Login.LoginWhich type, [Microsoft.AspNetCore.Mvc.FromQuery] Netnr.Login.AuthorizeResult result)
{
	(Netnr.Login.DocModel tokenResult, Netnr.Login.DocModel openidResult, Netnr.Login.DocModel userResult, Netnr.Login.PublicUserResult publicUser) = Netnr.Login.LoginTo.EntryOfSteps(type, result);
}

报错信息：
System.NullReferenceException: Object reference not set to an instance of an object.
   at Netnr.Login.LoginTo.EntryOfSteps(LoginWhich loginType, AuthorizeResult authResult)

微信登录使用相同的代码和Controller生成登录网址和登录后的回调，但没有报错。

**Comment by netnr** [comment]
提供报错的详细信息，最好是逐步的方式，看具体哪个方法出的问题

**Comment by LiveIsLive** [comment]
> 提供报错的详细信息，最好是逐步的方式，看具体哪个方法出的问题

报错信息：
System.NullReferenceException: Object reference not set to an instance of an object.
   at Netnr.Login.LoginTo.EntryOfSteps(LoginWhich loginType, AuthorizeResult authResult)

**Comment by netnr** [comment]
详细的堆栈信息

**Comment by LiveIsLive** [comment]
堆栈信息：

System.NullReferenceException: Object reference not set to an instance of an object.
   at Netnr.Login.LoginTo.EntryOfSteps(LoginWhich loginType, AuthorizeResult authResult)
   at ColdShine.Apis.Controllers.LoginController.Login(LoginWhich type, AuthorizeResult result) in G:\Test Projects\MyWebSite1\Apis\Controllers\LoginController.cs:line 19
   at lambda_method71(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Cache-Control: no-cache
Connection: close
Cookie: Hm_lvt_fafd8320c375a02b201a16533cd236a8=1723277059,1724158201,1725182219,1725453699
Host: www.core-hosting.net
Pragma: no-cache
Referer: https://core-hosting.net/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
sec-ch-ua-platform: "Windows"
sec-ch-ua: "Microsoft Edge";v="129", "Not=A?Brand";v="8", "Chromium";v="129"
sec-ch-ua-mobile: ?0
origin: https://core-hosting.net
sec-fetch-site: same-site
sec-fetch-mode: cors
sec-fetch-dest: empty
priority: u=1, i

**Comment by netnr** [comment]
G:\Test Projects\MyWebSite1\Apis\Controllers\LoginController.cs:line 19 行代码上下文看一下，感觉不像内部错误信息

**Comment by LiveIsLive** [comment]
第19行代码是Login方法里面的第一行EntryOfSteps，

```
public async Task<bool> Login(Netnr.Login.LoginWhich type, [Microsoft.AspNetCore.Mvc.FromQuery] Netnr.Login.AuthorizeResult result)
{
	(Netnr.Login.DocModel tokenResult, Netnr.Login.DocModel openidResult, Netnr.Login.DocModel userResult, Netnr.Login.PublicUserResult publicUser) = Netnr.Login.LoginTo.EntryOfSteps(type, result);
	this.RecordLoginUser(publicUser);
	// 2、创建用户声明信息
	var claims = new System.Security.Claims.Claim[]
	{
		new System.Security.Claims.Claim(System.Security.Claims.ClaimTypes.Name, publicUser.OpenId)
		//new Claim(ClaimTypes.MobilePhone, "13912345678")
	};
	// 3、创建声明身份证
	var claimIdentity = new System.Security.Claims.ClaimsIdentity(claims, Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationDefaults.AuthenticationScheme);
	// 4、创建声明身份证的持有者
	var claimPrincipal = new System.Security.Claims.ClaimsPrincipal(claimIdentity);
	// 5、登录
	await HttpContext.SignInAsync(claimPrincipal);
	return true;
}

```

**Comment by netnr** [comment]
按照示例代码里面的逐步方法 AuthCallback_Step 调用，看是哪个方法出的问题，我在本地调式没有报错

**Comment by LiveIsLive** [comment]
刚刚从GitHub下载了源代码编译了Debug版本，放上去之后输出的具体错误位置是LoginTo.cs这个文件的第960行

System.NullReferenceException: Object reference not set to an instance of an object.
   at Netnr.Login.LoginTo.EntryOfSteps(LoginWhich loginType, AuthorizeResult authResult) in G:\Libraries\Netnr.Login\LoginTo.cs:line 960

**Comment by netnr** [comment]
是不是 userResult.Raw 返回结果里面没得属性 alipay_user_info_share_response.gender 
可能账号没有完善这些个人信息，获取到的值为 null

改成这样再试试
```
publicUser.Gender = userObj.GetValue("gender")?.ToLower() == "m" ? 1 : 2;
```

**Comment by LiveIsLive** [comment]
考虑到Gender可能为空的情况，我是改成这样


```
publicUser.Gender = userObj.GetValue("gender")?.Equals("m", StringComparison.OrdinalIgnoreCase) switch
{
    true => 1,
    false => 2,
    _ => null
};
```
